auto: true
server: true
baseurl: /multilingual
permalink: /:categories/:title
languages:
  - name: 'English'
    key: 'en'
  - name: 'Español'
    key: 'es'

# Prose settings
prose:
  rooturl: '_posts'
